whoheplayfor/urls.py
"""WhoHePlayFor URL Configuration"""

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("djadmin/", admin.site.urls),
    path("", include("whpf.urls", namespace="whpf")),
]

whpf/urls.py
from django.urls import path

from . import views

app_name = "whpf"

urlpatterns = [
    path("", views.home, name="home"),
    path("tv/", views.tv, name="tv"),
    path("faq/", views.faq, name="faq"),
    path("save/<str:code>/", views.save, name="save"),
    path("results/<str:code>/", views.results, name="results"),
    path("scoreboard/", views.scoreboard, name="scoreboard"),
    path("score/<str:code>/", views.score, name="score"),
    path("stats/", views.stats, name="stats"),
    path("stats/<str:team_code>/", views.stats_team, name="stats_team"),
    path("right_guess/<int:pid>/", views.right_guess, name="right_guess"),
    path("wrong_guess/<int:pid>/", views.wrong_guess, name="wrong_guess"),
]

whpf/models.py
from __future__ import unicode_literals

import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from .managers import PlayerManager


class Options(models.Model):
    last_roster_update = models.DateTimeField()

    def __str__(self):
        return "Options"


class ModelWithDates(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Conference(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.name}ern conference"

    def get_teams(self):
        teams = Team.objects.none()
        for division in self.divisions.all():
            teams |= division.teams.all()
        return teams


class Division(models.Model):
    name = models.CharField(max_length=255)
    conference = models.ForeignKey(Conference, related_name="divisions", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} division"


class Team(ModelWithDates):
    nba_id = models.IntegerField()
    city = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    abbreviation = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    division = models.ForeignKey(Division, related_name="teams", on_delete=models.CASCADE)
    times_guessed = models.IntegerField(default=0)
    times_guessed_right = models.IntegerField(default=0)
    times_guessed_wrong = models.IntegerField(default=0)
    times_guessed_pct = models.IntegerField(default=0)

    class Meta:
        ordering = ["division__conference__name", "city", "name"]

    def __str__(self):
        return f"{self.city} {self.name}"

    @property
    def times_guessed_wrong_pct(self):
        return 100 - self.times_guessed_pct

    @property
    def picture(self):
        # TEAM_PICTURE_URL = "http://stats.nba.com/media/img/teams/"\
        #     "logos/%s_logo.svg"
        # TEAM_PICTURE_URL = "https://i.cdn.turner.com/nba/nba/assets/logos/"\
        #     "teams/primary/web/%s.svg"
        TEAM_PICTURE_URL = "https://cdn.nba.com/logos/nba/{team_id}/global/D/logo.svg"
        return TEAM_PICTURE_URL.format(team_id=self.nba_id)

    def stats_url(self):
        return reverse(
            "whpf:stats_team",
            kwargs={
                "team_code": self.code,
            },
        )


class Player(ModelWithDates):
    active = models.BooleanField(default=True)
    being_updated = models.BooleanField(default=False)
    nba_id = models.IntegerField()
    name = models.CharField(max_length=255)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    code = models.CharField(max_length=255)
    faceless = models.BooleanField(default=False)
    times_guessed = models.IntegerField(default=0)
    times_guessed_right = models.IntegerField(default=0)
    times_guessed_wrong = models.IntegerField(default=0)
    times_guessed_pct = models.IntegerField(default=0)

    all_players = models.Manager()
    objects = PlayerManager()

    def __str__(self):
        return self.name

    @property
    def times_guessed_wrong_pct(self):
        return 100 - self.times_guessed_pct

    @property
    def picture(self):
        DEFAULT = (
            "https://i.cdn.turner.com/nba/nba/.element/img/2.0/sect/"
            "statscube/players/large/default_nba_headshot_v2.png"
        )
        # PLAYER_PICTURE_URL = "http://i.cdn.turner.com/nba/nba/.element/"\
        #     "img/2.0/sect/statscube/players/large/%s.png"
        # PLAYER_PICTURE_URL = "https://ak-static.cms.nba.com/wp-content/"\
        #     "uploads/headshots/nba/latest/260x190/%s.png"
        PLAYER_PICTURE_URL = "https://cdn.nba.com/headshots/nba/latest/260x190/{}.png"
        if self.faceless:
            return DEFAULT
        return PLAYER_PICTURE_URL.format(self.nba_id)


class Result(ModelWithDates):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.TextField()
    score = models.IntegerField(default=0)

    class Meta:
        ordering = ["-score"]

    def __str__(self):
        return self.code

    # @property
    # def show_player_name(self):
    #     return self.code[:1] == '1'

    # @property
    # def shuffle_teams(self):
    #     return self.code[1:2] == '1'

    # @property
    # def time(self):
    #     return int(self.code[2:5])

    # @property
    # def rounds(self):
    #     return int(self.code[5:8])

    @property
    def parsed_code(self):
        from .helpers import parse_code

        return parse_code(self.code)

    def calculate_score(self):
        from .helpers import get_score

        self.score = get_score(self.code)
        self.save()
        return self.score


class Play(ModelWithDates):
    player = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    code = models.TextField()
    score = models.IntegerField(default=0)
    finished = models.BooleanField(default=False)
    legacy = models.BooleanField(default=False)

    def __str__(self):
        return self.code


class PlaySetting(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    play = models.ForeignKey(Play, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}: {self.value}"

whpf/forms.py
from django import forms

TIME_CHOICES = [
    (0, "Unlimited time"),
    (30, "30 seconds"),
    (60, "60 seconds"),
    (90, "90 seconds"),
]
ROUNDS_CHOICES = [
    (10, 10),
    (20, 20),
    (30, 30),
]
LIMIT_TEAMS_CHOICES = [
    ("0", "All teams"),
    ("1", "East teams"),
    ("2", "West teams"),
    ("3", "2016 Playoff teams (Current rosters)"),
    ("4", "2016 Finals (Current rosters)"),
    ("5", "2017 Playoff teams (Current rosters)"),
]


class GameForm(forms.Form):
    time = forms.ChoiceField(choices=TIME_CHOICES)
    rounds = forms.ChoiceField(choices=ROUNDS_CHOICES)
    limit_teams = forms.ChoiceField(choices=LIMIT_TEAMS_CHOICES)
    shuffle_teams = forms.BooleanField(required=False)
    show_player_name = forms.BooleanField(required=False)
    hard_mode = forms.BooleanField(required=False)

whpf/views.py
import json
from datetime import timedelta

from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import formats, timezone

from .forms import LIMIT_TEAMS_CHOICES, ROUNDS_CHOICES, TIME_CHOICES, GameForm
from .helpers import (
    get_guesses,
    get_score,
    get_teams_and_players_database,
    parse_code,
    request_is_ajax,
)
from .models import Options, Play, Player, PlaySetting, Result, Team


def _get_teams_and_players(game_info):
    """Get teams and players from the Database"""
    return get_teams_and_players_database(game_info)
    # return get_teams_and_players_api(game_info)


def home(request):
    """Main view
    If there's no POST or there's a POST but an invalid form,
    render home.html with GameForm with default values.
    If there's POST and the form is valid render whpf.html with
    the selected values.
    """
    TIME_DEFAULT = TIME_CHOICES[2][0]  # 60
    ROUNDS_DEFAULT = ROUNDS_CHOICES[1][0]  # 20
    LT_DEFAULT = LIMIT_TEAMS_CHOICES[0][0]  # 'all'
    SPN_DEFAULT = True
    SF_DEFAULT = False
    HM_DEFAULT = False

    # time = request.session.get('time', TIME_DEFAULT)
    # rounds = request.session.get('rounds', ROUNDS_DEFAULT)
    # limit_teams = request.session.get('limit_teams', LT_DEFAULT)
    # shuffle_teams = request.session.get('shuffle_teams', SF_DEFAULT)
    # show_player_name = request.session.get('show_player_name', SPN_DEFAULT)

    # form = GameForm(initial={
    #     'time': time,
    #     'rounds': rounds,
    #     'limit_teams': limit_teams,
    #     'shuffle_teams': shuffle_teams,
    #     'show_player_name': show_player_name,
    # })

    form = GameForm(
        initial={
            "time": TIME_DEFAULT,
            "rounds": ROUNDS_DEFAULT,
            "limit_teams": LT_DEFAULT,
            "shuffle_teams": SF_DEFAULT,
            "show_player_name": SPN_DEFAULT,
            "hard_mode": HM_DEFAULT,
        }
    )

    players_guessed_wrong = Player.objects.exclude(times_guessed=0).order_by("times_guessed_pct")[:3]

    # Weird behaviour of the Django ORM otherwise
    # players_guessed_wrong[0] returns the same as players_guessed_wrong[1]
    players_guessed_wrong = list(players_guessed_wrong)
    total_plays = Play.objects.count()

    if not request.POST:
        return render(
            request,
            "home.html",
            {
                "form": form,
                "players_guessed_wrong": players_guessed_wrong,
                "total_plays": total_plays,
            },
        )

    form = GameForm(request.POST)

    if not form.is_valid():
        return render(
            request,
            "home.html",
            {
                "form": form,
                "players_guessed_wrong": players_guessed_wrong,
                "total_plays": total_plays,
            },
        )

    time = int(form.cleaned_data["time"])
    rounds = int(form.cleaned_data["rounds"])
    limit_teams = form.cleaned_data["limit_teams"]
    shuffle_teams = form.cleaned_data["shuffle_teams"]
    show_player_name = form.cleaned_data["show_player_name"]
    hard_mode = form.cleaned_data["hard_mode"]

    if (
        time not in [x[0] for x in TIME_CHOICES]
        or rounds not in [x[0] for x in ROUNDS_CHOICES]
        or limit_teams not in [x[0] for x in LIMIT_TEAMS_CHOICES]
    ):
        raise Http404()

    game_info = {
        "time": time,
        "rounds": rounds,
        "limit_teams": limit_teams,
        "shuffle_teams": shuffle_teams,
        "show_player_name": show_player_name,
        "hard_mode": hard_mode,
    }

    (teams, players) = _get_teams_and_players(game_info)

    data = {
        "game_info": game_info,
        "players": players,
        "teams": teams,
    }

    if limit_teams == "0":
        data["west"] = teams[15:]
        data["east"] = teams[:15]

    p = Play()
    if request.user.is_authenticated:
        p.player = request.user
    p.save()

    for setting_name, setting_value in game_info.items():
        PlaySetting.objects.create(play=p, name=setting_name, value=str(setting_value))

    request.session["play_id"] = p.id
    return render(request, "whpf.html", data)


def tv(request):
    """Render a template showing a list of videos."""
    # videos = ['6psHr028Hyg', 'nvZt5d8RFr0', 'KbatKgTdRkM', 'cAIPKDBC4Mg', ]
    videos = [
        "8avNI5Tgzfs",  # 2021
        "xuJGzw8rzSs",  # 2020
        "5RbwsW_xDhE",  # 2018
        "kFt9M1ZzsEg",  # 2017
        "cRoHd1EIexs",  # 2016
        # 'zzfkvmobsoc',  # taken down
        "KbatKgTdRkM",  # 2012
        "nvZt5d8RFr0",  # 2011
    ]
    return render(request, "tv.html", {"videos": videos})


def faq(request):
    """Render a template showing a the frequently asked questions."""
    tv_url = reverse("whpf:tv")
    options = Options.objects.all()
    if options.exists():
        last_roster_update = formats.date_format(options.get().last_roster_update, "F jS, Y")
    else:
        last_roster_update = ""
    questions = [
        {"id": "whoareyou", "question": "Who are you?", "answer": "I'm Fepe. Hi."},
        {
            "id": "idea",
            "question": "Where did you get the idea to do this?",
            "answer": "<strong>Who He Play For?</strong> is a recurrent game "
            "on <a href='" + tv_url + "'>Inside the NBA</a>, where Ernie asks "
            "Chuck to guess where certain players play. And I've always "
            "found the idea fun to play. So I made it into a web game, so I "
            "(and you) can play it.",
        },
        {
            "id": "players",
            "question": "Which players are there?",
            "answer": "Even though on <a href='" + tv_url + "'>Inside the NBA</a> "
            "they usually use lesser known players, here you have all of "
            "them.<br />Alternatively you can try <strong>playing in "
            "<em>hard mode</em></strong> if you are looking for an extra "
            "challenge. That way, you'll get players from a pool of the 50 "
            "least guessed.<br />"
            "As a reward, if you are logged in, your score will be multiplied "
            "by 1,5 if you play in this mode. For more info, "
            "<a class='inlinefaq' href='#scores'> check how the scores are "
            "calculated</a>.",
        },
        {
            "id": "scores",
            "question": "How are scores calculated?",
            "answer": "<code>(difficulty * 3 * correct_guesses - wrong_guesses"
            ")</code> (rounded) where <code>wrong_guesses</code> include not "
            "only the ones you didn't guess right, but also the rounds you "
            "did not play. And <code>difficulty</code> is 1,5 if playing in "
            "<em>hard mode</em>, 1 otherwise.<br />"
            "<strike>It's a work in progress, so it can change anytime. "
            "For now, it's simply "
            "<code>(3*correct_guesses - wrong_guesses) * difficulty</code> "
            "where <code>wrong_guesses</code> include not only the ones you "
            "didn't guess right, but also the rounds you did not play.<br />"
            "And <code>difficulty</code> starts being 1, and adds up like so:"
            "<ul>"
            "<li>2 if the players name are not shown.</li>"
            "<li>1 if the teams are shuffled.</li>"
            "<li>1 if you are playing with every team.</li>"
            "<li>3 if you set the time limit to 30 seconds.</li>"
            "<li>2 if you set the time limit to 60 seconds.</li>"
            "<li>1 if you set the time limit to 90 seconds.</li>"
            "</ul>"
            "While <code>correct_guesses</code> and "
            "<code>wrong_guesses</code> are... well, you know.<br />"
            "I'll eventually come up with a better way to calculate scores "
            "but for now, this'll have to do."
            "<strong>Important</strong>: If you play without a time limit, "
            "you'll get a score of 0.</strike>",
        },
        {
            "id": "roster",
            "question": "How updated are the rosters?",
            "answer": "They are updated as of " + last_roster_update,
        },
        {
            "id": "sourcecode",
            "question": "What technology did you use to build this?",
            "answer": "It's mainly built with Python and JavaScript, running "
            "on <a href='https://www.djangoproject.com/'>Django Framework</a>."
            "<br/>If you want more info, the whole source-code is released "
            "open source on <a href='https://github.com/fepe55/whoheplayfor'>"
            "<i class='fa fa-github'></i> GitHub</a>.",
        },
        {
            "id": "shoutouts",
            "question": "Shout-outs",
            "answer": "For helping me with tips, testing, and more, "
            "shout-outs to Jess, SR, Alex Ntale, German, Duckie and Mora.",
        },
        {
            "id": "contact",
            "question": "I have a question / suggestion / complaint, how can " "I contact you?",
            "answer": "If what you want is not covered in this FAQ, you can "
            "find me at <a href='https://reddit.com/u/fepe55'>"
            "<i class='fa fa-reddit-alien'></i> /u/fepe55</a> and "
            "<a href='https://twitter.com/fepe55/'>"
            "<i class='fa fa-twitter'></i> fepe55</a>.<br/>"
            "If you want to know something about the code behind this, you "
            "can take a look at this project on "
            "<a href='https://github.com/fepe55/whoheplayfor'> "
            "<i class='fa fa-github'></i> GitHub</a>. And feel free to open "
            "an issue there if you see something wrong.",
        },
    ]

    # If, for some reason, we don't have a last_roster_update date, we delete
    # the question entirely
    if not last_roster_update:
        for q in questions:
            if q["id"] == "roster":

whpf/templates/header.html
{% load filters %}
{% load static %}
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'whpf:home' %}"><img src="{% static 'img/logo.svg' %}" alt="Who he play for" /></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'whpf:scoreboard' %}"><i class="fa fa-list-ol"></i> Scoreboard</a></li>
        <li><a href="{% url 'whpf:stats' %}"><i class="fa fa-pie-chart"></i> Stats</a></li>
        <li><a href="{% url 'whpf:tv' %}"><i class="fa fa-tv"></i> On NBA TV</a></li>
        <li><a href="{% url 'whpf:faq' %}"><i class="fa fa-question-circle"></i> FAQ</a></li>
        <!--
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Start new level <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Level 1</a></li>
            <li><a href="#">Level 2</a></li>
            <li><a href="#">Level 3</a></li>
            <li><a href="#">Level 4</a></li>
          </ul>
        </li>
        -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user and not user.is_anonymous %}
          {% with user_info=user|get_user_info %}
            <li class="navbar-text"><i class="{{ user_info.icon_class }}"></i> <span>{{ user.get_full_name|default:user.username }} (<a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>)</span></li>
          {% endwith %}
        {% else %}
          <li>
            <p class="navbar-text loginwith">Login using:</p>
          </li>
          <li>
              <a title="Reddit" href="{% url 'social:begin' 'reddit' %}?next={{ request.path }}">
                <i class="fa fa-reddit-alien"></i>
              </a>
          </li>
          <li>
              <a title="Google" href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">
                <i class="fa fa-google"></i>
              </a>
          </li>
          <li>
              <a title="Twitter" href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">
                <i class="fa fa-twitter"></i>
              </a>
          </li>
          <li>
              <a title="Facebook" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
                <i class="fa fa-facebook"></i>
              </a>
          </li>
        {% endif %}
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</nav>

whpf/templates/home.html
{% extends "base.html" %}
{% block content %}
  <div class="row home">
    <div class="col-md-12">
      {% if not user.is_authenticated %}
        <div class="alert alert-warning" role="alert">
          <i class="fa fa-exclamation-triangle"></i> If you want your score to be saved, log in in the top right before you start
        </div>
      {% endif %}
      <h1>Start a new game</h1>
      <div class="intro">
        <p>Do you know where does {{ players_guessed_wrong.0 }} play? And {{ players_guessed_wrong.1 }}? {{ players_guessed_wrong.2 }}?</p>
        <p>Based on the game <a href="{% url 'whpf:tv' %}">played on Inside The NBA</a>, comes the web version of <strong>Who He Play For?</strong></p>
        <p>Don't know how to play? Hit Start and I think you'll figure it out</p>
      </div>
      <form method="POST" class="form" id="mainform" action="{% url 'whpf:home' %}">
        {% csrf_token %}
        <div class="advanced-options">
          {% if user.is_authenticated %}
          <div class="alert alert-danger" role="alert">
            <i class="fa fa-exclamation-triangle"></i> If you change the advanced options, your score <strong>will not</strong> count towards the leaderboard. <a href="{% url 'whpf:home' %}">Reset the options</a>.
          </div>
          {% endif %}

          <div class="form-group">
            {{ form.time.errors }}
            <label for="{{ form.time.id_for_label }}">Time</label>
            {{ form.time }}
          </div>

          <div class="form-group">
            {{ form.rounds.errors }}
            <label for="{{ form.rounds.id_for_label }}">Rounds</label>
            {{ form.rounds }}
          </div>

          <div class="form-group">
            {{ form.limit_teams.errors }}
            <label for="{{ form.limit_teams.id_for_label }}">Limit teams</label>
            {{ form.limit_teams }}
          </div>

          <div class="form-group">
            {{ form.shuffle_teams.errors }}
            <label for="{{ form.shuffle_teams.id_for_label }}">Shuffle teams positions</label>
            {{ form.shuffle_teams }}
          </div>

          <div class="form-group">
            {{ form.show_player_name.errors }}
            <label for="{{ form.show_player_name.id_for_label }}">Show player name</label>
            {{ form.show_player_name }}
          </div>

          <div class="form-group hide">
            {{ form.hard_mode.errors }}
            <label for="{{ form.hard_mode.id_for_label }}">Hard mode</label>
            {{ form.hard_mode }}
          </div>

          <input type="checkbox" id="advanced" name="advanced" />
        </div>

        <div class="btn-group btn-group-justified start_game_buttons" role="group" aria-label="start game">
          <div class="btn-group" role="group">
            <button id="normal" class="btn btn-primary btn-lg start-game">Normal mode</button>
          </div>
          <div class="btn-group" role="group">
            <button id="hard" class="btn btn-danger btn-lg start-game">Hard mode</button>
          </div>
        </div>
        <a class="show-advanced-options" href="#">Show advanced options</a>

      </form>
      {% if last_roster_update %}
        <p class="muted text-right rosters-usage-info">Rosters updated as of <strong>{{ last_roster_update }}</strong><br /><a href="{% url 'whpf:home' %}"><strong>Who He Play For?</strong></a> has been played <strong>{{ total_plays }}</strong> times</p>
      {% endif %}
    </div>
  </div>
  {% comment %}
  <div class="row home" style="margin-top: 20px;">
    <div class="col-md-12">
      <div id="disqus_thread"></div>
      <script>

       var disqus_config = function () {
         this.page.url = "{{ request.build_absolute_uri }}";
         this.page.identifier = "home";
       };
      (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://whoheplayfor.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
      })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>
  </div>
  {% endcomment %}

{% endblock %}

{% block js %}
  <script>
    $("select").addClass("form-control");
  </script>

  <script>
  $(".start_game_buttons button").click(function(e){
    e.preventDefault();
    if ($(this).prop('id') == 'hard'){
      $("#id_hard_mode").prop("checked", true);
    }
    if ($(this).prop('id') == 'normal'){
      $("#id_hard_mode").prop("checked", false);
    }
    $("#mainform").submit();
  });
  </script>

  <script>
    $(".show-advanced-options").click(function(e){
      e.preventDefault();
      $(".advanced-options").slideDown();
      $("#advanced").prop("checked", true);
      $(this).hide();
    });
  </script>
{% endblock %}

whpf/templates/results.html
{% extends "base.html" %}
{% load filters %}
{% block content %}
  <div class="row result-guesses">
    <div class="col-md-12">
      <h1>
        Final score<small><a href="{% url 'whpf:faq' %}#scores"><sup>1</sup></a></small>: <span class="final_score">{{ score }}</span>

        {% if result %}
        {% with user_info=result.user|get_user_info %}
        <small>
          by
          {{ result.user.get_full_name|default:result.user.username }}
          {% if user_info.url %}
            (<a class="view-user-profile" title="View user profile" href="{{ user_info.url }}">
              <i class="{{ user_info.icon_class }}"></i>
            </a>)
          {% else %}
            (<i class="{{ user_info.icon_class }}"></i>)
          {% endif %}

        </small>
        {% endwith %}
        {% endif %}
      </h1>
      <h3>Game info</h3>
      <ul>
        {% if result %}<li>Date: {{ result.created }}</li>{% endif %}
        <li>Hard mode: {{ parsed_code.hard_mode|yesno:"Enabled,Disabled" }}</li>
        <li>Players named shown: {{ parsed_code.show_player_name|yesno }}</li>
        <li>Shuffled teams: {{ parsed_code.shuffle_teams|yesno }}</li>
        <li>Time limit: {{ parsed_code.time_limit }} seconds</li>
        <li>Time left: {{ parsed_code.time_left }} seconds</li>
        <li>Total rounds: {{ parsed_code.total_rounds }}</li>
        <li>Rounds actually played: {{ parsed_code.rounds_played }}</li>
      </ul>
      <h2>Guesses</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th>Your guess</th>
            <th>Correct guess</th>
          </tr>
        </thead>
        <tbody>
          {% for guess in guesses %}
          {% if guess.team.nba_id == guess.correct_team.nba_id %}
          <tr class="success">
          {% else %}
          <tr class="danger">
          {% endif %}
            <th scope="row" style="vertical-align: middle">
              <span class="fa-stack fa-2x">
                <i class="fa fa-circle fa-stack-2x"></i>
                <strong class="fa-stack-1x" style="color: white;">{{ forloop.counter }}</strong>
              </span>
            </th>
            <td><div class="text-center"><img src="{{ guess.player.picture }}" title="{{ guess.player.name }}" /><br />{{ guess.player.name }}</div></td>
            <td><img src="{{ guess.team.picture }}" title="{{ guess.team.city }} {{ guess.team.name }}" /></td>
            <td><img src="{{ guess.correct_team.picture }}" title="{{ guess.correct_team.city }} {{ guess.correct_team.name }}" /></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

whpf/templates/stats_team.html
{% extends "base.html" %}
{% block content %}

  <h1><img src="{{ team.picture }}" style="height: 70px;" />{{ team }}</h1>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
    <h3 id="wrong">Least guessed</h2>
    {% include 'stats_aux.html' with list=players_guessed_wrong %}
    </div>

    <div class="col-md-6 col-sm-6 col-xs-12">
    <h3 id="right">Most guessed</h2>
    {% include 'stats_aux.html' with list=players_guessed_right %}
    </div>

  </div>

{% endblock %}

{% block js %}
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>

{% endblock %}